config/routes.rb
Donkey::Application.routes.draw do
  resources :stables

end

app/models/stable.rb
class Stable < ActiveRecord::Base
  attr_accessible :number, :window
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stables_controller.rb
class StablesController < ApplicationController
  # GET /stables
  # GET /stables.json
  def index
    @stables = Stable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stables }
    end
  end

  # GET /stables/1
  # GET /stables/1.json
  def show
    @stable = Stable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stable }
    end
  end

  # GET /stables/new
  # GET /stables/new.json
  def new
    @stable = Stable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stable }
    end
  end

  # GET /stables/1/edit
  def edit
    @stable = Stable.find(params[:id])
  end

  # POST /stables
  # POST /stables.json
  def create
    @stable = Stable.new(params[:stable])

    respond_to do |format|
      if @stable.save
        format.html { redirect_to @stable, notice: 'Stable was successfully created.' }
        format.json { render json: @stable, status: :created, location: @stable }
      else
        format.html { render action: "new" }
        format.json { render json: @stable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stables/1
  # PUT /stables/1.json
  def update
    @stable = Stable.find(params[:id])

    respond_to do |format|
      if @stable.update_attributes(params[:stable])
        format.html { redirect_to @stable, notice: 'Stable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stables/1
  # DELETE /stables/1.json
  def destroy
    @stable = Stable.find(params[:id])
    @stable.destroy

    respond_to do |format|
      format.html { redirect_to stables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stables_helper.rb
module StablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donkey</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stables/_form.html.erb
<%= form_for(@stable) do |f| %>
  <% if @stable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stable.errors.count, "error") %> prohibited this stable from being saved:</h2>

      <ul>
      <% @stable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :window %><br />
    <%= f.check_box :window %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stables/edit.html.erb
<h1>Editing stable</h1>

<%= render 'form' %>

<%= link_to 'Show', @stable %> |
<%= link_to 'Back', stables_path %>

app/views/stables/index.html.erb
<h1>Listing stables</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Window</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stables.each do |stable| %>
  <tr>
    <td><%= stable.number %></td>
    <td><%= stable.window %></td>
    <td><%= link_to 'Show', stable %></td>
    <td><%= link_to 'Edit', edit_stable_path(stable) %></td>
    <td><%= link_to 'Destroy', stable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stable', new_stable_path %>

app/views/stables/new.html.erb
<h1>New stable</h1>

<%= render 'form' %>

<%= link_to 'Back', stables_path %>

app/views/stables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @stable.number %>
</p>

<p>
  <b>Window:</b>
  <%= @stable.window %>
</p>


<%= link_to 'Edit', edit_stable_path(@stable) %> |
<%= link_to 'Back', stables_path %>